// Generated by scripts/prepare-edge.js from server/domain.js. Do not edit.
import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";
import { inflateSync } from "node:zlib";

export class HttpError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}
export const hash = (value) => createHash("sha256").update(value).digest("hex");
export const object = (x) =>
  x !== null && typeof x === "object" && !Array.isArray(x);
export function stable(value) {
  if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`;
  if (object(value))
    return `{${Object.keys(value)
      .sort()
      .map((k) => `${JSON.stringify(k)}:${stable(value[k])}`)
      .join(",")}}`;
  return JSON.stringify(value);
}
function requireText(value, field, max = 1000) {
  if (typeof value !== "string" || !value.trim() || value.length > max)
    throw new HttpError(
      400,
      `${field} must be a nonempty string (maximum ${max} characters).`,
    );
  return value;
}
export function crc32(bytes) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let n = 0; n < 8; n++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
}
export function validatePng(bytes) {
  if (
    bytes.length < 57 ||
    bytes.length > 8 * 1024 * 1024 ||
    !bytes.subarray(0, 8).equals(Buffer.from("89504e470d0a1a0a", "hex"))
  )
    throw new HttpError(400, "Viewport must be a valid PNG, up to 8 MB.");
  let pos = 8,
    width,
    height,
    depth,
    color,
    end = false;
  const compressed = [];
  while (pos + 12 <= bytes.length) {
    const size = bytes.readUInt32BE(pos),
      type = bytes.toString("ascii", pos + 4, pos + 8);
    if (pos + 12 + size > bytes.length)
      throw new HttpError(400, "Truncated PNG.");
    if (
      crc32(bytes.subarray(pos + 4, pos + 8 + size)) !==
      bytes.readUInt32BE(pos + 8 + size)
    )
      throw new HttpError(400, "PNG checksum is invalid.");
    const data = bytes.subarray(pos + 8, pos + 8 + size);
    if (pos === 8 && (type !== "IHDR" || size !== 13))
      throw new HttpError(400, "PNG header is invalid.");
    if (type === "IHDR") {
      if (width !== undefined)
        throw new HttpError(400, "Duplicate PNG header.");
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      depth = data[8];
      color = data[9];
      if (
        !width ||
        !height ||
        width > 8192 ||
        height > 8192 ||
        width * height > 16_000_000 ||
        ![0, 2, 3, 4, 6].includes(color) ||
        ![1, 2, 4, 8, 16].includes(depth) ||
        data[10] ||
        data[11] ||
        data[12] !== 0
      )
        throw new HttpError(
          400,
          "Unsupported PNG: use a non-interlaced viewport up to 16 megapixels.",
        );
      if (
        (color === 3 && depth === 16) ||
        ([2, 4, 6].includes(color) && depth < 8)
      )
        throw new HttpError(400, "Invalid PNG bit depth.");
    }
    if (type === "IDAT") compressed.push(data);
    pos += size + 12;
    if (type === "IEND") {
      if (size !== 0) throw new HttpError(400, "Invalid PNG end.");
      end = true;
      break;
    }
  }
  if (!end || pos !== bytes.length || !compressed.length)
    throw new HttpError(400, "Incomplete PNG.");
  const channels = { 0: 1, 2: 3, 3: 1, 4: 2, 6: 4 }[color];
  const stride = Math.ceil((width * channels * depth) / 8) + 1;
  try {
    const pixels = inflateSync(Buffer.concat(compressed), {
      maxOutputLength: 130_000_000,
    });
    if (pixels.length !== stride * height) throw new Error();
    for (let y = 0; y < height; y++)
      if (pixels[y * stride] > 4) throw new Error();
  } catch {
    throw new HttpError(400, "PNG image data is invalid.");
  }
  return { width, height };
}
export function validateEnvelope(body) {
  if (!object(body) || !object(body.event))
    throw new HttpError(400, "Expected { event, viewport }.");
  const event = structuredClone(body.event);
  if (Buffer.byteLength(JSON.stringify(event)) > 512 * 1024)
    throw new HttpError(413, "Event metadata exceeds 512 KB.");
  if (event.schemaVersion !== 2)
    throw new HttpError(400, "Only Fusion event schemaVersion 2 is supported.");
  if (event.eventType !== "design_checkpoint")
    throw new HttpError(400, "Expected a design_checkpoint event.");
  requireText(event.source, "event.source", 100);
  requireText(event.timestamp, "event.timestamp", 80);
  if (
    !/T.*(?:Z|[+-]\d{2}:\d{2})$/.test(event.timestamp) ||
    !Number.isFinite(Date.parse(event.timestamp))
  )
    throw new HttpError(
      400,
      "event.timestamp must be an ISO timestamp with timezone.",
    );
  if (!object(event.document))
    throw new HttpError(400, "event.document is required.");
  requireText(event.document.name, "document.name", 300);
  const documentKey = event.document.key || event.document.dataFileId;
  requireText(
    documentKey,
    "document.key or document.dataFileId (use a stable local ID for unsaved files)",
    1000,
  );
  if (
    !Array.isArray(event.engineeringChanges) ||
    event.engineeringChanges.length > 500
  )
    throw new HttpError(
      400,
      "engineeringChanges must be an array of at most 500 changes.",
    );
  for (const change of event.engineeringChanges) {
    if (!object(change))
      throw new HttpError(400, "Each engineering change must be an object.");
    requireText(change.action, "engineeringChanges.action", 100);
    if (
      change.properties !== undefined &&
      (!Array.isArray(change.properties) ||
        change.properties.some((p) => !object(p)))
    )
      throw new HttpError(
        400,
        "Change properties must be an array of objects.",
      );
  }
  if (
    event.rationale !== undefined &&
    (typeof event.rationale !== "string" || event.rationale.length > 10000)
  )
    throw new HttpError(400, "Rationale must be text up to 10,000 characters.");
  if (event.changes !== undefined && !object(event.changes))
    throw new HttpError(400, "Raw changes must be an object.");
  if (
    event.changeCount !== undefined &&
    event.changeCount !== event.engineeringChanges.length
  )
    throw new HttpError(
      400,
      "changeCount must equal engineeringChanges.length.",
    );
  if (
    event.rawChangeCount !== undefined &&
    (!Number.isSafeInteger(event.rawChangeCount) || event.rawChangeCount < 0)
  )
    throw new HttpError(400, "rawChangeCount must be a nonnegative integer.");
  const viewport = body.viewport;
  if (!object(viewport) || viewport.contentType !== "image/png")
    throw new HttpError(400, "A top-level image/png viewport is required.");
  requireText(viewport.filename, "viewport.filename", 255);
  const base64 = viewport.base64;
  if (
    typeof base64 !== "string" ||
    !base64.length ||
    base64.length > 11_184_812 ||
    base64.length % 4 ||
    !/^[A-Za-z0-9+/]*={0,2}$/.test(base64)
  )
    throw new HttpError(
      400,
      "viewport.base64 must contain canonical base64 PNG bytes.",
    );
  const image = Buffer.from(base64, "base64");
  if (image.toString("base64") !== base64)
    throw new HttpError(400, "Invalid base64.");
  const dimensions = validatePng(image);
  // Local upload responses and machine paths are not checkpoint identity.
  const identity = {
    schemaVersion: event.schemaVersion,
    eventType: event.eventType,
    source: event.source,
    timestamp: event.timestamp,
    document: event.document,
    engineeringChanges: event.engineeringChanges,
    changes: event.changes ?? {},
    rationale: event.rationale ?? "",
    image: hash(image),
  };
  const fingerprint = hash(stable(identity));
  const clientId = event.id ?? event.eventId;
  if (clientId !== undefined) requireText(clientId, "event.id", 200);
  return {
    event,
    image,
    dimensions,
    documentKey,
    fingerprint,
    dedupeKey: clientId ? `client:${clientId}` : `sha256:${fingerprint}`,
  };
}
export function present(row, detail = false) {
  const event = row.raw_event;
  const result = {
    id: row.id,
    documentId: row.document_id,
    documentName: event.document.name,
    capturedAt: row.captured_at,
    receivedAt: row.received_at,
    source: event.source,
    status: row.status,
    ai: row.ai,
    aiProvider: row.ai_provider,
    aiModel: row.ai_model,
    error: row.error,
    rationale: event.rationale ?? "",
    engineeringChanges: event.engineeringChanges,
    changeCount: event.engineeringChanges.length,
    rawChangeCount: event.rawChangeCount ?? null,
    document: event.document,
    imageUrl: `/api/events/${row.id}/image`,
    image: { bytes: row.image_bytes, ...row.image_dimensions },
  };
  if (detail) result.rawEvent = event;
  return result;
}
