// Generated by scripts/prepare-edge.js from server/supabase-store.js. Do not edit.
import { Buffer } from "node:buffer";
import { HttpError } from "./domain.js";

export class SupabaseStore {
  constructor(config, fetcher = fetch) {
    this.config = config;
    this.fetch = fetcher;
  }
  async request(
    path,
    { method = "GET", body, headers = {}, binary = false } = {},
  ) {
    const response = await this.fetch(`${this.config.supabaseUrl}${path}`, {
      method,
      headers: {
        apikey: this.config.serviceKey,
        ...(this.config.serviceKey.startsWith("sb_secret_")
          ? {}
          : { Authorization: `Bearer ${this.config.serviceKey}` }),
        ...(body && !Buffer.isBuffer(body)
          ? { "Content-Type": "application/json" }
          : {}),
        ...headers,
      },
      body: body
        ? Buffer.isBuffer(body)
          ? body
          : JSON.stringify(body)
        : undefined,
      signal: AbortSignal.timeout(30_000),
    });
    if (!response.ok) {
      // Never expose database errors, SQL or provider credentials to the UI.
      console.error(
        "Supabase request failed:",
        method,
        path.split("?")[0],
        response.status,
      );
      throw new HttpError(
        502,
        "Storage service is unavailable. The upload can be retried safely.",
      );
    }
    if (binary) return Buffer.from(await response.arrayBuffer());
    const text = await response.text();
    return text ? JSON.parse(text) : null;
  }
  async rpc(name, body = {}) {
    return this.request(`/rest/v1/rpc/${name}`, { method: "POST", body });
  }
  query(table, filters) {
    return `/rest/v1/${table}?${new URLSearchParams(filters)}`;
  }
  async ingest(owner, input) {
    const result = await this.rpc("trace_ingest", {
      p_owner: owner,
      p_key: input.dedupeKey,
      p_fingerprint: input.fingerprint,
      p_document_key: input.documentKey,
      p_event: input.event,
      p_bytes: input.image.length,
      p_dimensions: input.dimensions,
    });
    if (result.conflict) throw new HttpError(409, result.conflict);
    let row = result.row;
    if (row.status === "receiving") {
      // Deterministic object paths make concurrent/retried uploads safe. A failed
      // upload leaves 'receiving' state and is repaired by the same POST retry.
      await this.request(
        `/storage/v1/object/${this.config.bucket}/${row.image_path}`,
        {
          method: "POST",
          body: input.image,
          headers: { "Content-Type": "image/png", "x-upsert": "true" },
        },
      );
      await this.request(
        this.query("trace_events", {
          id: `eq.${row.id}`,
          owner_id: `eq.${owner}`,
          status: "eq.receiving",
          deleted_at: "is.null",
        }),
        { method: "PATCH", body: { status: "pending" } },
      );
      row = await this.get(owner, row.id);
      if (!row)
        throw new HttpError(409, "Checkpoint was deleted during upload.");
    }
    return { row, duplicate: result.duplicate };
  }
  async get(owner, id) {
    return (
      (
        await this.request(
          this.query("trace_events", {
            owner_id: `eq.${owner}`,
            id: `eq.${id}`,
            deleted_at: "is.null",
            limit: "1",
          }),
        )
      )[0] || null
    );
  }
  async image(row) {
    return this.request(
      `/storage/v1/object/authenticated/${this.config.bucket}/${row.image_path}`,
      { binary: true },
    );
  }
  async list(owner, { documentId, status, q, cursor, limit = 30 } = {}) {
    const filters = {
      owner_id: `eq.${owner}`,
      deleted_at: "is.null",
      order: "captured_at.desc,id.desc",
      limit: String(limit),
    };
    if (documentId) filters.document_id = `eq.${documentId}`;
    if (status) filters.status = `eq.${status}`;
    if (q) filters.search_text = `ilike.%${q.replace(/[%_*\\]/g, "")}%`;
    if (cursor)
      filters.or = `(captured_at.lt.${cursor.time},and(captured_at.eq.${cursor.time},id.lt.${cursor.id}))`;
    return this.request(this.query("trace_events", filters));
  }
  async documents(owner) {
    return this.request(
      this.query("trace_document_overview", {
        owner_id: `eq.${owner}`,
        order: "latest_at.desc",
      }),
    );
  }
  async claim() {
    return (await this.rpc("trace_claim"))[0] || null;
  }
  async settle(row, result, error) {
    const status = error
      ? row.attempts < 3
        ? "pending"
        : "failed"
      : "complete";
    await this.request(
      this.query("trace_events", {
        id: `eq.${row.id}`,
        lease_id: `eq.${row.lease_id}`,
        deleted_at: "is.null",
      }),
      {
        method: "PATCH",
        body: {
          status,
          ai: result?.ai ?? null,
          ai_provider: result?.provider ?? null,
          ai_model: result?.model ?? null,
          prompt_version: result?.promptVersion ?? null,
          error,
          available_at: new Date(
            Date.now() + row.attempts * 5000,
          ).toISOString(),
          lease_until: null,
        },
      },
    );
  }
  async recoverExhausted() {
    await this.rpc("trace_recover");
  }
  async retry(owner, id) {
    const rows = await this.request(
      this.query("trace_events", {
        owner_id: `eq.${owner}`,
        id: `eq.${id}`,
        status: "eq.failed",
        deleted_at: "is.null",
      }),
      {
        method: "PATCH",
        headers: { Prefer: "return=representation" },
        body: {
          status: "pending",
          attempts: 0,
          available_at: new Date().toISOString(),
          error: null,
        },
      },
    );
    return rows.length > 0;
  }
  async delete(owner, id) {
    const rows = await this.request(
      this.query("trace_events", {
        owner_id: `eq.${owner}`,
        id: `eq.${id}`,
        deleted_at: "is.null",
      }),
      {
        method: "PATCH",
        headers: { Prefer: "return=representation" },
        body: { deleted_at: new Date().toISOString(), raw_event: {}, ai: null },
      },
    );
    // The durable tombstone prevents re-ingestion. Cleanup is retried by the worker.
    return rows.length > 0;
  }
  async cleanup() {
    const rows = await this.request(
      this.query("trace_events", {
        deleted_at: "not.is.null",
        image_deleted: "eq.false",
        limit: "20",
      }),
    );
    for (const row of rows) {
      // Delay cleanup beyond the upload/AI request timeout to avoid in-flight writes.
      if (Date.parse(row.deleted_at) > Date.now() - 180_000) continue;
      await this.request(`/storage/v1/object/${this.config.bucket}`, {
        method: "DELETE",
        body: { prefixes: [row.image_path] },
      });
      await this.request(this.query("trace_events", { id: `eq.${row.id}` }), {
        method: "PATCH",
        body: { image_deleted: true },
      });
    }
  }
  async createToken(owner, token) {
    await this.request("/rest/v1/trace_tokens", {
      method: "POST",
      body: { ...token, owner_id: owner },
    });
  }
  async tokens(owner) {
    return this.request(
      this.query("trace_tokens", {
        owner_id: `eq.${owner}`,
        select: "id,name,prefix,created_at,revoked_at",
        order: "created_at.desc",
      }),
    );
  }
  async tokenOwner(digest) {
    return (
      await this.request(
        this.query("trace_tokens", {
          token_hash: `eq.${digest}`,
          revoked_at: "is.null",
          select: "owner_id",
          limit: "1",
        }),
      )
    )[0]?.owner_id;
  }
  async revokeToken(owner, id) {
    const rows = await this.request(
      this.query("trace_tokens", {
        id: `eq.${id}`,
        owner_id: `eq.${owner}`,
        revoked_at: "is.null",
      }),
      {
        method: "PATCH",
        headers: { Prefer: "return=representation" },
        body: { revoked_at: new Date().toISOString() },
      },
    );
    return rows.length > 0;
  }
  close() {}
}
