import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

// Keep the desktop and Edge API on identical validation, storage and AI logic.
// Edge deployments include only these pure modules, never local credentials.
const root = new URL("../", import.meta.url);
const destination = new URL("supabase/functions/_shared/", root);
await mkdir(destination, { recursive: true });
for (const name of [
  "domain.js",
  "supabase-store.js",
  "ai.js",
  "zip.js",
  "design-report.js",
]) {
  const source = await readFile(new URL(`server/${name}`, root), "utf8");
  const bufferImport = /\bBuffer\b/.test(source)
    ? 'import { Buffer } from "node:buffer";\n'
    : "";
  await writeFile(
    new URL(name, destination),
    `// Generated by scripts/prepare-edge.js from server/${name}. Do not edit.\n${bufferImport}${source}`,
    "utf8",
  );
}
console.log(`Prepared shared Edge modules in ${fileURLToPath(destination)}`);
